### ISSUE TITLE
No module named 'shapely'

### ISSUE THREAD

**Issue by HaydenHu** [julianteuber/kicad-vias-along-path#1]
![image](https://user-images.githubusercontent.com/30103277/177286263-df29dc79-d7ea-4b3a-a0f3-adbebf2a79a2.png)
kicad6.0.6_1
win10

**Comment by ghost** [comment]
Sorry for the late response.
One dependency for the plug-in to work is installing the shapely python package.
I added this to the README with Commit a2a7152.
